Module5 task2
htmlacademy-react/6616-what-to-watch-9 pull request #7
Opened 2022-03-07 18:57 UTC by alexeyzuby

2022-03-07 19:11 UTC, alexeyzuby commented
Привет! Посмотри, пожалуйста, насколько логично и оптимально был сделан компонент с табами.
И по поводу похожих фильмов - попробовал сделать начальный компонент filmsList более умным, но показалось что в будущем это может стрельнуть в ногу. Пока выделил похожие в отдельный компонент + в дальнейшем пересоберу filmsList, чтобы он включал в себя сортировку и тд. И подумаю как быть со списком любимых фильмов. Но пока не хочется их собирать в один монструозный компонент.

2022-03-10 08:47 UTC, sahaviev commented on project/src/components/film-tabs/film-tabs.tsx
> +  }
Эту логику я бы написал внизу где уже вставляешь **currentTab** следующим образом:
```
{current === TabsItems.Overview && <TabOverview film={film}/>}
{current === TabsItems.Details && <TabDetails film={film}/>}
{current === TabsItems.Reviews && <TabReviews reviews={reviews}/>}
```
Переменная **currentTab** не нужна будет

2022-03-10 08:48 UTC, sahaviev commented on project/src/components/film-tabs/film-tabs.tsx
> +import TabReviews from './tab-reviews';
Слово Tab правильнее ставить после названия типа: **OverviewTab**, **DetailsTab**, **ReviewsTab**...

2022-03-10 10:50 UTC, sahaviev commented on project/src/components/film-tabs/tab-details.tsx
> +const getRuntimeStr = (minutes: number): string => {
getRuntimeStr - я бы лучше назвал getFormattedDuration или как-то так. Без постфикса _str_.

2022-03-10 11:02 UTC, sahaviev commented on project/src/components/film-tabs/tab-details.tsx
> +            })}
Это лучше записать в таком формате: `film.starring.join(',<br />')`

2022-03-10 11:04 UTC, sahaviev commented on project/src/components/film-tabs/tab-overview.tsx
> +    <Fragment>
Здесь можно использовать сокращенную форму Fragment'ов: <></>

2022-03-10 11:05 UTC, sahaviev commented on project/src/components/film-tabs/tab-reviews.tsx
> +        ))}
То что тут 2 цикла вместо 1(предварительно разбив фильмы по группа) лично я не считаю сильно ужасным, но кто-то сказал бы переделать)

2022-03-10 13:35 UTC, sahaviev commented on project/src/components/similar-films/similar-films.tsx
> +  );
Это лучше переписать вот так:
```
if (filmsList.length === 0) {
   return "No Similar Films...";
} 
return (
    <>
      <h2 className="catalog__title">More like this</h2>
      <div className="catalog__films-list">
        {filmsList.map((film) => (
          <FilmCard
            key={film.id}
            film={film}
            isActive={film.id === activeFilmId}
            onHover={setActiveFilmId}
          />
        ))}
      </div>
    </>
  );
```

2022-03-10 13:38 UTC, sahaviev requested changes
Привет!

У тебя очень аккуратный код. Замечания из большиства те которые на мой взгляд сделают его чище и лучше.

2022-03-11 21:18 UTC, alexeyzuby commented on project/src/components/film-tabs/tab-reviews.tsx
> +        ))}
Вынес фильтрацию в отдельные переменные, но все равно пока еще есть сомнения в правильности решения этой задачи) Если есть сомнения, то я обязательно улучшу этот момент в следующих заданиях.
Хитрое все же такое место с этими двумя колонками.

2022-03-13 20:05 UTC, sahaviev commented on project/src/components/film-tabs/overview-tab.tsx
> +        <p className="film-card__starring"><strong>Starring: {filmStarring} and other</strong></p>
Вместо создания переменной filmStarring, можно прям тут написать `Starring: {film.starring.join(', ')}`

2022-03-13 20:06 UTC, sahaviev commented on project/src/components/film-tabs/reviews-tab.tsx
> +      </div>
Пока что этот код стал хуже с точки зрения количества шагов в цикле.
Но потом это уже обсудим) Я приму так

2022-03-13 20:07 UTC, sahaviev approved these changes
Почти все ок!

2022-03-13 20:07 UTC, merged